# 配置 r2dbc 数据源
spring:
  r2dbc:
    username: root
    password: root
    # 注意要 r2dbc 开头
    url: r2dbc:mysql://localhost:3306/webflux_example?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
